ARG APP_IMAGE
FROM $APP_IMAGE

ENV APP_HOME /app
WORKDIR $APP_HOME

# Install test dependencies.
RUN pip install -r test_requirements.txt

ENV TOKEN=test_token

CMD exec pytest /app/tests/ --cov=. --cov-fail-under=70
